### PR TITLE
Add option testing package after build

### PR DESCRIPTION
**Pull request by dpvpro**

### CODE REVIEW

**Comment by dawidd6** [comment]
There already is -no-lintian flag. This seems unnecessary to me.

**Comment by dpvpro** [comment]
Some packages generate error when they are installed for test

**Comment by dawidd6** [comment]
Specific example please. I'd like to see what's wrong.

**Comment by dpvpro** [comment]
Error occurs when i try to build "linux" source package. I can't repoduce now error. It seems that there was issue with my source package. I build old source package on conatainer with new package base.

**Pull request closed without merging**
